#!/bin/bash

MASTER_BRANCH_LOCAL=master

git switch $MASTER_BRANCH_LOCAL
git rebase
git switch -

for LOOP_BRANCH_NAME in $(git for-each-ref --format="%(refname:short)" refs/heads | grep -v $MASTER_BRANCH_LOCAL); do
	git switch $LOOP_BRANCH_NAME
	git rebase --autostash
	git switch -
done;
